_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  conditional_fields: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_block: 0
  entity_reference_revisions: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  language: 0
  layout_builder: 0
  layout_builder_admin_theme: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  redirect: 0
  redirect_404: 0
  rename_admin_paths: 0
  search: 0
  securitytxt: 0
  shortcut: 0
  svg_image_field: 0
  system: 0
  tamper: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  weight: 0
  ds: 1
  pathauto: 1
  ds_extras: 2
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  claro: 0
  stable9: 0
  interledger: 0
profile: standard
