_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en-gb
uuid: 02effb3e-94f6-41d6-b2ea-a4d0091a4daa
name: 'Interledger Foundation'
mail: huijing@interledger.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en-gb
mail_notification: null
